spring.datasource.url=jdbc:postgresql://localhost:5432/agencia_viagens
spring.datasource.username=postgres
spring.datasource.password=Jr347347

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true